import { products } from "@/lib/site";
import type { CampaignStoreState } from "./types";

const firstServe = products.find((p) => p.slug === "first-serve")!;
const secondWind = products.find((p) => p.slug === "second-wind")!;

export const SEED_STATE: CampaignStoreState = {
  organizations: [
    {
      id: "org-riverside",
      name: "Riverside Volleyball Club",
      type: "club",
      slug: "riverside-volleyball-club",
      contactEmail: "coach@riversidevc.example",
      // Configured share for this org — not implied by club vs nonprofit.
      bagShareCents: 400,
      createdAt: "2026-08-12T14:00:00.000Z",
    },
    {
      id: "org-athens",
      name: "Athens Youth Foundation",
      type: "nonprofit",
      slug: "athens-youth-foundation",
      contactEmail: "hello@athensyouth.example",
      bagShareCents: 250,
      createdAt: "2026-08-20T15:30:00.000Z",
    },
  ],
  athletes: [
    {
      id: "athlete-maya",
      organizationId: "org-riverside",
      name: "Maya Chen",
      email: "maya@riversidevc.example",
      createdAt: "2026-08-14T16:00:00.000Z",
    },
    {
      id: "athlete-jordan",
      organizationId: "org-riverside",
      name: "Jordan Hale",
      email: "jordan@riversidevc.example",
      createdAt: "2026-08-14T16:05:00.000Z",
    },
    {
      id: "athlete-sam",
      organizationId: "org-athens",
      name: "Sam Ortiz",
      email: "sam@athensyouth.example",
      createdAt: "2026-08-22T18:00:00.000Z",
    },
  ],
  campaigns: [
    {
      id: "camp-maya",
      organizationId: "org-riverside",
      athleteId: "athlete-maya",
      name: "Maya's Season Fund",
      slug: "maya-season-fund",
      story:
        "Help Maya cover travel, club dues, and tournament fees this club season. Every bag of Next Point coffee ships from us — the club earns its configured share on each bag.",
      goalBags: 40,
      status: "live",
      createdAt: "2026-08-15T12:00:00.000Z",
      publishedAt: "2026-09-01T13:00:00.000Z",
    },
    {
      id: "camp-jordan",
      organizationId: "org-riverside",
      athleteId: "athlete-jordan",
      name: "Jordan's Court Campaign",
      slug: "jordan-court-campaign",
      story:
        "Jordan is raising bags for the spring showcase circuit. This campaign is still a draft — publish it from the Next Point Coffee admin to go live.",
      goalBags: 30,
      status: "draft",
      createdAt: "2026-09-10T12:00:00.000Z",
      publishedAt: null,
    },
    {
      id: "camp-sam",
      organizationId: "org-athens",
      athleteId: "athlete-sam",
      name: "Sam's Court Time",
      slug: "sam-court-time",
      story:
        "Athens Youth Foundation puts kids on the court who otherwise sit out. Buy a roast and fund the next practice.",
      goalBags: 50,
      status: "live",
      createdAt: "2026-08-24T12:00:00.000Z",
      publishedAt: "2026-09-02T14:00:00.000Z",
    },
  ],
  sales: [
    {
      id: "sale-maya-1",
      campaignId: "camp-maya",
      organizationId: "org-riverside",
      athleteId: "athlete-maya",
      productSlug: firstServe.slug,
      productName: firstServe.name,
      quantity: 2,
      amountCents: firstServe.priceCents * 2,
      shippingCents: 650,
      amountOwedCents: 800,
      currency: "usd",
      buyerName: "Priya Shah",
      buyerEmail: "priya@example.com",
      source: "simulated",
      stripeSessionId: null,
      payoutPeriodId: null,
      booksSyncStatus: "stubbed",
      createdAt: "2026-09-16T15:22:00.000Z",
    },
    {
      id: "sale-maya-2",
      campaignId: "camp-maya",
      organizationId: "org-riverside",
      athleteId: "athlete-maya",
      productSlug: secondWind.slug,
      productName: secondWind.name,
      quantity: 3,
      amountCents: secondWind.priceCents * 3,
      shippingCents: 650,
      amountOwedCents: 1200,
      currency: "usd",
      buyerName: "Coach Alvarez",
      buyerEmail: "alvarez@example.com",
      source: "simulated",
      stripeSessionId: null,
      payoutPeriodId: null,
      booksSyncStatus: "stubbed",
      createdAt: "2026-09-18T19:05:00.000Z",
    },
    {
      id: "sale-maya-3",
      campaignId: "camp-maya",
      organizationId: "org-riverside",
      athleteId: "athlete-maya",
      productSlug: firstServe.slug,
      productName: firstServe.name,
      quantity: 3,
      amountCents: firstServe.priceCents * 3,
      shippingCents: 650,
      amountOwedCents: 1200,
      currency: "usd",
      buyerName: "The Chen Family",
      buyerEmail: "family@example.com",
      source: "simulated",
      stripeSessionId: null,
      payoutPeriodId: null,
      booksSyncStatus: "stubbed",
      createdAt: "2026-09-20T11:40:00.000Z",
    },
    {
      id: "sale-sam-1",
      campaignId: "camp-sam",
      organizationId: "org-athens",
      athleteId: "athlete-sam",
      productSlug: firstServe.slug,
      productName: firstServe.name,
      quantity: 3,
      amountCents: firstServe.priceCents * 3,
      shippingCents: 650,
      amountOwedCents: 750,
      currency: "usd",
      buyerName: "Neighborhood Boosters",
      buyerEmail: "boosters@example.com",
      source: "simulated",
      stripeSessionId: null,
      payoutPeriodId: null,
      booksSyncStatus: "stubbed",
      createdAt: "2026-09-17T17:10:00.000Z",
    },
  ],
  payouts: [],
  users: [
    {
      id: "user-admin",
      role: "admin",
      name: "Next Point Coffee Admin",
      email: "admin@nextpointcoffee.com",
    },
    {
      id: "user-club-riverside",
      role: "club",
      name: "Coach Rivera",
      email: "coach@riversidevc.example",
      organizationId: "org-riverside",
    },
    {
      id: "user-club-athens",
      role: "club",
      name: "Alex Kim",
      email: "hello@athensyouth.example",
      organizationId: "org-athens",
    },
    {
      id: "user-athlete-maya",
      role: "athlete",
      name: "Maya Chen",
      email: "maya@riversidevc.example",
      organizationId: "org-riverside",
      athleteId: "athlete-maya",
    },
    {
      id: "user-athlete-jordan",
      role: "athlete",
      name: "Jordan Hale",
      email: "jordan@riversidevc.example",
      organizationId: "org-riverside",
      athleteId: "athlete-jordan",
    },
    {
      id: "user-athlete-sam",
      role: "athlete",
      name: "Sam Ortiz",
      email: "sam@athensyouth.example",
      organizationId: "org-athens",
      athleteId: "athlete-sam",
    },
  ],
  campaignRequests: [
    {
      id: "req-westside",
      organizationName: "Westside Boosters",
      organizationType: "club",
      contactName: "Riley Nguyen",
      contactEmail: "riley@westsideboosters.example",
      phone: "555-0142",
      city: "Columbus, OH",
      athleteName: "Avery Cole",
      notes: "We want a spring travel-ball fundraiser. Coach will share the link with families once Next Point Coffee sets it up.",
      status: "new",
      createdAt: "2026-09-19T18:30:00.000Z",
      handledAt: null,
    },
  ],
  booksEvents: [
    {
      id: "evt-sale-maya-1",
      type: "sale.recorded",
      version: 1,
      occurredAt: "2026-09-16T15:22:00.000Z",
      payload: { saleId: "sale-maya-1", campaignId: "camp-maya", athleteId: "athlete-maya" },
      syncStatus: "stubbed",
      lastError: null,
    },
    {
      id: "evt-sale-maya-2",
      type: "sale.recorded",
      version: 1,
      occurredAt: "2026-09-18T19:05:00.000Z",
      payload: { saleId: "sale-maya-2", campaignId: "camp-maya", athleteId: "athlete-maya" },
      syncStatus: "stubbed",
      lastError: null,
    },
    {
      id: "evt-sale-maya-3",
      type: "sale.recorded",
      version: 1,
      occurredAt: "2026-09-20T11:40:00.000Z",
      payload: { saleId: "sale-maya-3", campaignId: "camp-maya", athleteId: "athlete-maya" },
      syncStatus: "stubbed",
      lastError: null,
    },
    {
      id: "evt-sale-sam-1",
      type: "sale.recorded",
      version: 1,
      occurredAt: "2026-09-17T17:10:00.000Z",
      payload: { saleId: "sale-sam-1", campaignId: "camp-sam", athleteId: "athlete-sam" },
      syncStatus: "stubbed",
      lastError: null,
    },
  ],
};
